"""add isapproved to Answers

Revision ID: 0926690477a2
Revises: 7225740ee78f
Create Date: 2025-08-19 21:11:57.032518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0926690477a2'
down_revision: Union[str, Sequence[str], None] = '7225740ee78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_approved')
    op.drop_column('answers', 'is_approved')
    # ### end Alembic commands ###
