"""add deletedwhen to Questions

Revision ID: 0dce7ffe2162
Revises: 574a2341d210
Create Date: 2025-08-20 13:59:55.022731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dce7ffe2162'
down_revision: Union[str, Sequence[str], None] = '574a2341d210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('last_delete', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('last_delete', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'last_delete')
    op.drop_column('answers', 'last_delete')
    # ### end Alembic commands ###
