"""add deletedwhen to Questions

Revision ID: 17d5ea2cd825
Revises: bf9dfcce76f5
Create Date: 2025-08-20 13:56:03.002902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d5ea2cd825'
down_revision: Union[str, Sequence[str], None] = 'bf9dfcce76f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('last_delete', sa.DateTime(), nullable=False))
    op.add_column('questions', sa.Column('last_delete', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'last_delete')
    op.drop_column('answers', 'last_delete')
    # ### end Alembic commands ###
