"""add votetime to answer votes

Revision ID: 23b2cd1ea05f
Revises: a2c91e52c251
Create Date: 2025-08-15 21:56:20.905558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b2cd1ea05f'
down_revision: Union[str, Sequence[str], None] = 'a2c91e52c251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer votes',
    sa.Column('voteid', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('ans_id', sa.Integer(), nullable=True),
    sa.Column('votetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ans_id'], ['answers.answid'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['questions.qstid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('voteid'),
    sa.UniqueConstraint('user_id', 'ans_id', name='unique_answer_vote')
    )
    op.add_column('votes', sa.Column('votetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'votetime')
    op.drop_table('answer votes')
    # ### end Alembic commands ###
