"""add isdeleted to Questions

Revision ID: 429f74611abf
Revises: 0dce7ffe2162
Create Date: 2025-08-20 14:32:42.827891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429f74611abf'
down_revision: Union[str, Sequence[str], None] = '0dce7ffe2162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_deleted')
    op.drop_column('answers', 'is_deleted')
    # ### end Alembic commands ###
