"""Remove upvotes and downvotes from questions

Revision ID: 48104a520d4a
Revises: bc06c6764ba1
Create Date: 2025-08-11 15:52:49.061273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48104a520d4a'
down_revision: Union[str, Sequence[str], None] = 'bc06c6764ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
