"""add points, streaks, level, and bio to users

Revision ID: 6b1921f033fd
Revises: 75e7fd7846d0
Create Date: 2025-08-15 10:02:04.450334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1921f033fd'
down_revision: Union[str, Sequence[str], None] = '75e7fd7846d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'level')
    op.drop_column('users', 'streak')
    op.drop_column('users', 'points')
    # ### end Alembic commands ###
