"""add points, streaks, level, and bio to users

Revision ID: 75e7fd7846d0
Revises: ca6023c4870f
Create Date: 2025-08-15 09:44:44.672215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e7fd7846d0'
down_revision: Union[str, Sequence[str], None] = 'ca6023c4870f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
