"""add lastupdate to Users

Revision ID: 875da275b399
Revises: aaa1a0e3c8e9
Create Date: 2025-08-18 18:19:51.099061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875da275b399'
down_revision: Union[str, Sequence[str], None] = 'aaa1a0e3c8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_streak_value', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_streak_value')
    # ### end Alembic commands ###
