"""add votetime to Votes

Revision ID: 888bb656233d
Revises: 6b1921f033fd
Create Date: 2025-08-15 21:45:48.121724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888bb656233d'
down_revision: Union[str, Sequence[str], None] = '6b1921f033fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer votes',
    sa.Column('voteid', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('ans_id', sa.Integer(), nullable=True),
    sa.Column('votetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ans_id'], ['answers.answid'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['questions.qstid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('voteid'),
    sa.UniqueConstraint('user_id', 'ans_id', name='unique_user_vote')
    )
    op.add_column('votes', sa.Column('votetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'votetime')
    op.drop_table('answer votes')
    # ### end Alembic commands ###
