"""add isprivate and private_key to groups

Revision ID: 9e04134b905d
Revises: e8f4944faaac
Create Date: 2025-09-01 03:12:53.747027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e04134b905d'
down_revision: Union[str, Sequence[str], None] = 'e8f4944faaac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('isprivate', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('private_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'private_key')
    op.drop_column('groups', 'isprivate')
    # ### end Alembic commands ###
