"""Added upvotes column to Groups

Revision ID: bc06c6764ba1
Revises: 
Create Date: 2025-08-11 15:41:05.570503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc06c6764ba1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('questions', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('downvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'downvotes')
    op.drop_column('questions', 'upvotes')
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
