"""add isprivate and private_key to groups

Revision ID: e8f4944faaac
Revises: 414c36036c90
Create Date: 2025-09-01 03:10:30.133703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f4944faaac'
down_revision: Union[str, Sequence[str], None] = '414c36036c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('isprivate', sa.Boolean(), nullable=False))
    op.add_column('groups', sa.Column('private_key', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'private_key')
    op.drop_column('groups', 'isprivate')
    # ### end Alembic commands ###
