"""Remove upvotes and downvotes from questions

Revision ID: fde8695aafa5
Revises: 48104a520d4a
Create Date: 2025-08-11 15:55:02.514520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde8695aafa5'
down_revision: Union[str, Sequence[str], None] = '48104a520d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'upvotes')
    op.drop_column('questions', 'downvotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
